# Generated by Django 3.1.1 on 2021-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('landmark', models.TextField(max_length=40)),
            ],
        ),
    ]
