# Generated by Django 3.1.1 on 2021-01-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktApp', '0003_hotel_instructor_ponywalla_skilender_skishop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSkiShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.skishop')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSkiLender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.skilender')),
            ],
        ),
        migrations.CreateModel(
            name='PhonePonyWalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.ponywalla')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneHut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.hut')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktApp.hotel')),
            ],
        ),
    ]
